### ISSUE TITLE
 Cannot read property 'readFile' of undefined

### ISSUE THREAD

**Issue by Calvin66** [bimspot/xeokit-converter#7]
root@85baf9147ab7:/data# gltf2xkt -s scene.gltf -o scene.xkt

Reading glTF file: scene.gltf
Converting to XKT format: 3
Something went wrong: TypeError: Cannot read property 'readFile' of undefined
    at main (/usr/local/lib/node_modules/@xeokit/xeokit-gltf-to-xkt/gltf2xkt.js:74:34)
    at Object.<anonymous> (/usr/local/lib/node_modules/@xeokit/xeokit-gltf-to-xkt/gltf2xkt.js:79:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

**Comment by eriadam** [comment]
Hey @Calvin66 , thanks for reporting this. Can you please let me know your environment?

**Comment by Calvin66** [comment]
Docker for Windows

**Comment by eriadam** [comment]
@Calvin66 Thanks. I meant node and npm version, base image, etc. What is your use case, how do you add your files to the container?
